import {
	PRIVATE_ACTIVITY_LIST,
	PRIVATE_DASHBOARD,
	PRIVATE_MARKET,
	PRIVATE_TWO_FACTOR
} from '../../src/actions/state/routes';

export const privateRoutes = [PRIVATE_DASHBOARD, PRIVATE_ACTIVITY_LIST, PRIVATE_MARKET, PRIVATE_TWO_FACTOR];
